/**
 * Emoji offered by the caption editor's picker.
 *
 * A curated static list rather than a picker library, for the same reason the device
 * and font catalogues are static TypeScript: it is coupled to the renderer. Every
 * picker worth installing paints its grid from Apple or Twemoji artwork served off a
 * CDN, and what lands in the document is a *character* that Konva then draws in
 * whatever emoji font the machine has. Picking from images would mean choosing one
 * glyph and exporting a different one — and on a store screenshot, that is the whole
 * job. The grid below is plain text, so it shows exactly what the canvas will draw.
 *
 * It is also why there is no CDN fetch here: the editor works on an anonymous local
 * draft with no account, and a picker that needs the network to open would be the
 * only part of it that does.
 *
 * Deliberately a few hundred rather than the full set. The inspector is a narrow
 * column, these are app-store captions, and search covers the rest of the intent.
 * Each entry is `[character, search terms]`.
 */

export interface EmojiGroup {
  id: string;
  label: string;
  /** A member of the group, used as its tab — no icon set to keep in sync. */
  tab: string;
  emoji: readonly (readonly [string, string])[];
}

export const EMOJI_GROUPS = [
  {
    id: "popular",
    label: "Popular",
    tab: "✨",
    emoji: [
      ["✨", "sparkles shine magic new"],
      ["🚀", "rocket launch fast ship startup"],
      ["🔥", "fire hot trending popular"],
      ["⭐", "star favourite rating"],
      ["🌟", "glowing star shine"],
      ["💡", "bulb idea tip light"],
      ["✅", "check tick done complete yes"],
      ["🎉", "party tada celebrate launch"],
      ["💪", "muscle strong power"],
      ["❤️", "heart love red"],
      ["👏", "clap applause praise"],
      ["🙌", "raised hands celebrate praise"],
      ["🏆", "trophy win award best"],
      ["📈", "chart up growth increase"],
      ["⚡", "lightning bolt fast power energy"],
      ["🎯", "target goal aim focus"],
      ["💎", "gem diamond premium quality"],
      ["🔒", "lock secure privacy safe"],
    ],
  },
  {
    id: "smileys",
    label: "Smileys & people",
    tab: "😀",
    emoji: [
      ["😀", "grinning smile happy"],
      ["😃", "smiley happy joy"],
      ["😄", "smile happy laugh"],
      ["😁", "beaming grin"],
      ["😆", "laughing satisfied"],
      ["😅", "sweat smile relief"],
      ["🤣", "rolling laughing rofl"],
      ["😂", "joy tears laugh"],
      ["🙂", "slight smile"],
      ["😉", "wink"],
      ["😊", "blush smile happy"],
      ["😇", "innocent halo angel"],
      ["🥰", "smiling hearts love"],
      ["😍", "heart eyes love"],
      ["🤩", "star struck amazed wow"],
      ["😘", "kiss blow"],
      ["😋", "yum tasty delicious"],
      ["😎", "sunglasses cool"],
      ["🤓", "nerd glasses study"],
      ["🧐", "monocle inspect"],
      ["🤔", "thinking hmm"],
      ["🤗", "hug"],
      ["🥳", "partying celebrate birthday"],
      ["😴", "sleeping tired zzz"],
      ["😮", "open mouth surprised wow"],
      ["😢", "cry sad tear"],
      ["😭", "sob crying sad"],
      ["😅", "nervous sweat"],
      ["🙃", "upside down silly"],
      ["😐", "neutral meh"],
      ["🤯", "mind blown exploding head"],
      ["👋", "wave hello hi bye"],
      ["👍", "thumbs up like yes good"],
      ["👎", "thumbs down dislike no"],
      ["🤝", "handshake deal partner"],
      ["🙏", "pray thanks please"],
      ["👀", "eyes look watch"],
      ["🧠", "brain smart learn"],
      ["👨‍💻", "man technologist developer coding"],
      ["👩‍💻", "woman technologist developer coding"],
    ],
  },
  {
    id: "nature",
    label: "Animals & nature",
    tab: "🌿",
    emoji: [
      ["🐶", "dog puppy pet"],
      ["🐱", "cat kitten pet"],
      ["🐭", "mouse"],
      ["🦊", "fox"],
      ["🐻", "bear"],
      ["🐼", "panda"],
      ["🐨", "koala"],
      ["🦁", "lion"],
      ["🐮", "cow"],
      ["🐷", "pig"],
      ["🐸", "frog"],
      ["🐵", "monkey"],
      ["🦄", "unicorn magic"],
      ["🐝", "bee honey"],
      ["🦋", "butterfly"],
      ["🐢", "turtle slow"],
      ["🐬", "dolphin"],
      ["🐳", "whale"],
      ["🌱", "seedling grow plant new"],
      ["🌿", "herb leaf plant green"],
      ["🍀", "clover luck"],
      ["🌸", "blossom flower spring"],
      ["🌺", "hibiscus flower"],
      ["🌻", "sunflower"],
      ["🌈", "rainbow pride colour"],
      ["☀️", "sun sunny day"],
      ["🌙", "moon night dark"],
      ["⛅", "cloud sun weather"],
      ["❄️", "snowflake cold winter"],
      ["🌊", "wave ocean sea water"],
    ],
  },
  {
    id: "food",
    label: "Food & drink",
    tab: "🍎",
    emoji: [
      ["🍎", "apple fruit"],
      ["🍌", "banana fruit"],
      ["🍓", "strawberry fruit"],
      ["🍇", "grapes fruit"],
      ["🍊", "orange fruit"],
      ["🥑", "avocado healthy"],
      ["🥦", "broccoli vegetable healthy"],
      ["🥗", "salad healthy food"],
      ["🍞", "bread"],
      ["🧀", "cheese"],
      ["🍔", "burger food fast"],
      ["🍟", "fries food"],
      ["🍕", "pizza food"],
      ["🌮", "taco food"],
      ["🍣", "sushi food"],
      ["🍜", "noodles ramen food"],
      ["🍪", "cookie biscuit"],
      ["🍰", "cake slice dessert"],
      ["🎂", "birthday cake celebrate"],
      ["🍫", "chocolate"],
      ["🍿", "popcorn movie"],
      ["☕", "coffee cup drink hot"],
      ["🍵", "tea drink"],
      ["🥤", "cup straw drink soda"],
      ["🍺", "beer drink"],
      ["🥂", "cheers toast celebrate"],
      ["🍷", "wine drink"],
      ["💧", "droplet water"],
    ],
  },
  {
    id: "activity",
    label: "Activity",
    tab: "⚽",
    emoji: [
      ["⚽", "football soccer sport"],
      ["🏀", "basketball sport"],
      ["🏈", "american football sport"],
      ["⚾", "baseball sport"],
      ["🎾", "tennis sport"],
      ["🏐", "volleyball sport"],
      ["🏓", "table tennis ping pong"],
      ["🏸", "badminton"],
      ["🥊", "boxing fight"],
      ["🏋️", "weight lifting gym fitness"],
      ["🧘", "yoga meditate calm"],
      ["🏃", "running run exercise"],
      ["🚴", "cycling bike"],
      ["🏊", "swimming swim"],
      ["🎮", "game controller gaming play"],
      ["🕹️", "joystick arcade game"],
      ["🎲", "dice game random"],
      ["🎨", "art palette paint design"],
      ["🎵", "music note song"],
      ["🎧", "headphones listen audio"],
      ["🎤", "microphone sing podcast"],
      ["🎬", "clapper movie film video"],
      ["📷", "camera photo"],
      ["🎁", "gift present reward"],
      ["🥇", "gold medal first win"],
      ["🎪", "circus tent"],
    ],
  },
  {
    id: "travel",
    label: "Travel & places",
    tab: "✈️",
    emoji: [
      ["🚗", "car drive"],
      ["🚕", "taxi cab"],
      ["🚌", "bus"],
      ["🚲", "bicycle bike"],
      ["🛴", "scooter"],
      ["🏍️", "motorcycle"],
      ["✈️", "airplane flight travel"],
      ["🚀", "rocket space launch"],
      ["🚂", "train rail"],
      ["🚢", "ship boat"],
      ["🗺️", "map travel navigate"],
      ["🧭", "compass direction navigate"],
      ["📍", "pin location place"],
      ["🏠", "house home"],
      ["🏢", "office building work"],
      ["🏥", "hospital health"],
      ["🏦", "bank money"],
      ["🏫", "school education learn"],
      ["🌍", "earth globe world europe africa"],
      ["🌎", "earth globe world americas"],
      ["🌏", "earth globe world asia"],
      ["🗽", "statue liberty new york"],
      ["🗼", "tower tokyo"],
      ["🏝️", "island beach holiday"],
      ["⛰️", "mountain hike"],
      ["🌃", "night city stars"],
    ],
  },
  {
    id: "objects",
    label: "Objects",
    tab: "📱",
    emoji: [
      ["📱", "phone mobile smartphone app"],
      ["💻", "laptop computer work"],
      ["🖥️", "desktop computer monitor"],
      ["⌚", "watch time wearable"],
      ["🖨️", "printer"],
      ["🔋", "battery power charge"],
      ["🔌", "plug power"],
      ["💾", "floppy save disk"],
      ["📀", "disc storage"],
      ["📡", "satellite signal network"],
      ["🔍", "search magnify find"],
      ["🔑", "key access login"],
      ["🔐", "locked key secure"],
      ["🛡️", "shield security protect"],
      ["🔔", "bell notification alert"],
      ["📣", "megaphone announce marketing"],
      ["📝", "memo note write edit"],
      ["📅", "calendar date schedule"],
      ["⏰", "alarm clock time reminder"],
      ["⏳", "hourglass time waiting"],
      ["📚", "books learn study read"],
      ["✏️", "pencil write edit"],
      ["📌", "pushpin pin save"],
      ["📎", "paperclip attach"],
      ["🗂️", "folders organise files"],
      ["🛒", "cart shopping buy"],
      ["💰", "money bag cash"],
      ["💳", "credit card pay payment"],
      ["🧾", "receipt invoice bill"],
      ["🎓", "graduation cap education course"],
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    tab: "❤️",
    emoji: [
      ["❤️", "heart love red"],
      ["🧡", "orange heart"],
      ["💛", "yellow heart"],
      ["💚", "green heart"],
      ["💙", "blue heart"],
      ["💜", "purple heart"],
      ["🖤", "black heart"],
      ["💖", "sparkling heart love"],
      ["💯", "hundred perfect score"],
      ["✅", "check tick done yes"],
      ["☑️", "checkbox ticked done"],
      ["❌", "cross no wrong error"],
      ["⚠️", "warning caution alert"],
      ["❓", "question help"],
      ["❗", "exclamation important"],
      ["➕", "plus add"],
      ["➖", "minus remove"],
      ["🔄", "refresh sync reload"],
      ["🔺", "up triangle increase"],
      ["🔻", "down triangle decrease"],
      ["▶️", "play start"],
      ["⏸️", "pause"],
      ["🔊", "speaker sound volume audio"],
      ["🔇", "mute silent"],
      ["♾️", "infinity unlimited"],
      ["©️", "copyright"],
      ["®️", "registered trademark"],
      ["™️", "trademark"],
      ["🔵", "blue circle dot"],
      ["🟢", "green circle dot online"],
    ],
  },
] as const satisfies readonly EmojiGroup[];

/** Every entry, flattened once for search rather than per keystroke. */
export const ALL_EMOJI = EMOJI_GROUPS.flatMap((group) =>
  group.emoji.map(([character, terms]) => ({ character, terms })),
);
